@url=http://localhost:4001


@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoibWFya0BnbWFpbC5jb20iLCJyb2xlIjoidmVuZG9yIiwiaWF0IjoxNzUxNTIzMjQ5LCJleHAiOjE3NTE1MjQxNDl9.EbUk3H3VLT2GPNpKGX53b6zLv61y5yAsdBwDh6ng3wY
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUzNjMzMjE4LCJleHAiOjE3NTM3MTk2MTh9.25r_HsQDO8JAR38uRjG2UplNY5bGQkbDYmWSsVAfkn4

@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0LCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTU0MzE4NywiZXhwIjoxNzUxNTQ0MDg3fQ.0ovBnvKZgQh4zunVqx2ReVVQtN10XaEKtXocKRClWX0
@vendor_token =
@customer_token =
#### sign In ####
POST {{url}}/auth/signin
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin123"
}


#### CREATE NEW PROFILE ####
POST {{url}}/profile
Content-Type: application/json

{
  "firstName": "Getrude",
  "lastName": "Cheptoo",
  "email": "cheptoog677@gmail.com",
  "password": "getrude123",
  "role": "customer",
  "phone": "1212121210"
}
#### GET ALL PROFILES ####
GET {{url}}/profile
Authorization: Bearer {{accessToken}}

#### GET PROFILE BY ID ####
GET {{url}}/profile/1
Authorization: Bearer {{accessToken}}

###  UPDATE PROFILE BY ID ###
PATCH {{url}}/profile/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "phone": "1234567890"
}

### DELETE PROFILE BY ID ###
DELETE {{url}}/profile/40
Authorization: Bearer {{accessToken}}

#### SEED DATABASE ####
POST {{url}}/seed


#### CREATE NEW VENDOR ####
POST {{url}}/vendors
Content-Type: application/json

{ 
  "profileId": 9,
  "business_name": "The Master Car Wash",
  "phone": "00011223344",
  "tax_id": "0944654333",
  "address": "456 Elm St, City, Country",
  "status": "Inactive"

}
#### GET ALL VENDORS ####
GET {{url}}/vendors
Authorization: Bearer {{accessToken}}

#### GET VENDOR BY ID ####
GET {{url}}/vendors/1

### UPDATE VENDOR BY ID ###
PATCH {{url}}/vendors/7
Content-Type: application/json

{ 
  "phone": "123455670",
  "status": "InActive"
  
}

#### DELETE VENDOR BY ID ####
DELETE {{url}}/vendors/1



### CREATE NEW CUSTOMER ####
POST {{url}}/customer
Content-Type: application/json

{
  "profileId": 47,
  "phone": "12745600",
  "address": "123456789"
}

#### GET ALL CUSTOMERS ####
GET {{url}}/customer
Authorization:  Bearer {{accessToken}}

#### GET CUSTOMER BY ID ####
GET {{url}}/customer/1
Authorization: Bearer {{accessToken}}

#### UPDATE CUSTOMER BY ID ###
PATCH {{url}}/customer/2
Content-Type: application/json

{
  "phone_number": "1234567811"
}

#### DELETE CUSTOMER BY ID ####
DELETE {{url}}/customer/47


#### CREATE NEW ADMIN ####
POST {{}}/admins
Content-Type: application/json

{
  ""
}

#### GET ALL ADMINS ####
GET {{url}}/admins

#### GET ADMIN BY ID ####
GET {{url}}/admins/1

#### UPDATE ADMIN BY ID ####
PATCH {{url}}/admins/1
Content-Type: application/json

{
  ""
}

#### DELETE ADMIN BY ID ####
DELETE {{url}}/admins/1

#### CREATE NEW BOOKING ####
POST {{url}}/bookings
Content-Type: application/json

{
  "customerId": 1,
  "serviceName": "Premium Wash",
  "vendorName": "June's Car Wash",
  "vehiclePlateNo": "KBX1234",
  "scheduled_at": "2023-10-01T10:00:00Z",
  "payment_method": "credit_card"
}
#### GET ALL BOOKINGS ####
GET {{url}}/bookings

#### GET BOOKING BY ID ####
GET {{url}}/bookings/1

#### GET BOOKINGS BY Vendor ID ####
GET {{url}}/bookings/vendor/1

#### GET BOOKINGS BY CUSTOMER ID ####
GET {{url}}/bookings/customer/1


#### UPDATE BOOKING BY ID ####
PATCH {{url}}/bookings/1
Content-Type: application/json

{
  "payment_status": "unpaid"
}
### UPDATE BOOKING STATUS BY ID ####
PATCH {{url}}/bookings/1/status
Content-Type: application/json

{
  "status": "cancelled"
}
#### DELETE BOOKING BY ID ####
DELETE {{url}}/bookings/1

#### CREATE NEW VEHICLE ####
POST {{url}}/vehicles
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "customer_id": 2,
  "make": "Benz",
  "model": "A4",
  "year": 2023,
  "color": "Yellow",
  "license_plate": "KBX1234"
} 

#### GET ALL VEHICLES ####
GET {{url}}/vehicles

#### GET VEHICLE BY ID ####
GET {{url}}/vehicles/3
#### GET VEHICLES BY CUSTOMER ID ####
GET {{url}}/vehicles/customer/1

#### UPDATE VEHICLE BY ID ####
PATCH {{url}}/vehicles/1
Content-Type: application/json

{
  "make": "Honda",
  "model": "Civic",
  "year": 2021,
  "color": "Red",
  "license_plate": "XYZ1234"
}

#### DELETE VEHICLE BY ID ####
DELETE {{url}}/vehicles/4

#### CREATE NEW SERVICE ####
POST {{url}}/services
Content-Type: application/json

{
  "name": "Ultimate Wash",
  "description": " A premium wash service with extra care",
  "price": "29.99",
  "duration": "60",
  "vendorId": "1"
}

#### GET ALL SERVICES ####
GET {{url}}/services

#### GET SERVICE BY ID ####
GET {{url}}/services/3

#### GET SERVICES BY VENDOR ID ####
GET {{url}}/services/vendor/1

#### UPDATE SERVICE BY ID ####
PATCH {{url}}/services/8
Content-Type: application/json

{
  "price": "3000"
}

#### DELETE SERVICE BY ID ####
DELETE {{url}}/services/4

#### CREATE NEW REVIEW ####
POST {{url}}/reviews
Content-Type: application/json

{
  "customer_id": 2,
  "vendor_id": 8,
  "booking_id": 9,
  "vehicle_id": 6,
  "service_id": 3,
  "rating": 3,
  "comment": "Average service, not worth the price."
}

#### GET ALL REVIEWS ####
GET {{url}}/reviews

#### GET REVIEW BY ID ####
GET {{url}}/reviews/15

#### GET REVIEWS BY CUSTOMER ID ####
GET {{url}}/reviews/customer/1

#### GET REVIEWS BY VENDOR ID ####
GET {{url}}/reviews/vendor/1

#### UPDATE REVIEW BY ID ####
PATCH {{url}}/reviews/15
Content-Type: application/json

{
  "rating": 4,
  "comment": "Good service, but could be better."
}

#### DELETE REVIEW BY ID ####
DELETE {{url}}/reviews/1

### CALL CHAT API ####
POST {{url}}/chat
Content-Type: application/json

{
  "messages": [
    {
      "role": "user",
      "content": "Hi, can you help me wash my car?"
    },
    {
      "role": "assistant",
      "content": "Sure! When would you like to book?"
    }
  ]
}

#### CREATE NEW PAYMENT ####
POST {{url}}/payments/initialize
Content-Type: application/json

{
  "amount": 100.00,
  "booking_id": 7,
  "first_name": "John",
  "last_name": "Doe",
  "email": "customer@example.com",
  "phone_number": "0712345678",
  "payment_method": "credit_card"
}
#### VERIFY PAYMENT ####
GET {{url}}/payments/verify/pay_1753218748659_734539
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### GET PAYMENT BY ID ###
GET {{url}}/payments/1
Authorization: Bearer {{accessToken}}

#### GET ALL PAYMENTS ####
GET {{url}}/payments
Authorization: Bearer {{accessToken}}

# {
#   "reference": "pay_1234567890"
# }

### UPLOAD IMAGES ###

POST {{url}}/images/upload
Content-Type: multipart/form-data

file=@C:\Users\user\OneDrive\Pictures\Camera Roll\IMG-20250705-WA0016[1].jpg

# {
#   "file": "{{file}}"
# }

### Upload image to NestJS API
POST http://localhost:4001/images/upload
Content-Type: multipart/form-data

file=@C:/Users/user/OneDrive/Pictures/Camera Roll/IMG-20250705-WA0016[1].jpg

